// Central content for the 7Golden «اخبار و اطلاعیه‌ها» (News & Announcements) page.
//
// Every item below is grounded in the brand's own verified facts (see
// corporate-content.js): work began ۱۳۷۷ in a small Qazvin workshop; the company
// «شرکت خشکبار و بسته‌بندی هفت طلایی» was registered in ۱۳۹۶; raw material is
// bought straight from growers via the family بنکداری (خشکبار محمدی, 100+ years);
// pistachio comes from Buin-Zahra (Qazvin) and Kerman, hazelnut from Oshnavieh,
// Alamut (Qazvin) and northern Ashkvarat; exports go to the UAE, Qatar, Oman,
// Iraq and Afghanistan (plus Europe via traders).
//
// Do NOT introduce invented numbers, tonnage or certification claims here.

export const NEWS_CATEGORIES = {
  announcement: { label: 'اطلاعیه', tone: 'var(--gold-2)' },
  exhibition: { label: 'نمایشگاه', tone: '#8ab4f8' },
  export: { label: 'صادرات', tone: '#7fd1ae' },
  production: { label: 'تولید', tone: '#e0a36a' },
  quality: { label: 'کیفیت', tone: '#c9a0dc' },
};

// The announcements feed. `body` is an array of paragraphs shown in the detail modal.
export const NEWS_ITEMS = [
  {
    id: 'expo-food-industry',
    category: 'exhibition',
    date: '۱۴۰۴/۰۵/۱۸',
    title: 'حضور هفت‌طلایی در نمایشگاه صنایع غذایی و شیرینی',
    excerpt: 'غرفه هفت‌طلایی در نمایشگاه تخصصی صنایع غذایی، مغز فندق، خلال پسته و بادام صنعتی را برای کارخانه‌های شکلات، قنادی و بستنی عرضه می‌کند.',
    body: [
      'هفت‌طلایی در نمایشگاه تخصصی صنایع غذایی و شیرینی، محصولات فرآوری‌شده فندق، پسته و بادام را برای کارخانه‌های شکلات، قنادی و بستنی به نمایش می‌گذارد.',
      'در این غرفه، نمونه‌های مغز فندق خام و رست، خمیر و گرانول فندق، مغز و خلال پسته و پرک بادام درختی در گریدهای صنعتی ارائه می‌شود.',
      'کارشناسان واحد بازرگانی برای گفت‌وگو درباره تأمین عمده، مشخصات گریدها و زمان‌بندی تحویل در غرفه حضور دارند.',
    ],
    image: '/gallery/AQ8A1499AQ8A1499.webp',
    featured: true,
  },
  {
    id: 'direct-hazelnut-sourcing',
    category: 'production',
    date: '۱۴۰۴/۰۴/۳۰',
    title: 'تأمین مستقیم مغز فندق از اشنویه و الموت قزوین',
    excerpt: 'فندق از باغ‌های اشنویه، الموت قزوین و اشکوارات شمال — بدون واسطه و از طریق بنکداری خانوادگی خشکبار محمدی — تأمین می‌شود.',
    body: [
      'فندق مورد استفاده در خط فرآوری، مستقیم از باغ‌های اشنویه، الموت قزوین و اشکوارات شمال خریداری می‌شود.',
      'این تأمین از طریق بنکداری خانوادگی خشکبار محمدی با بیش از صد سال قدمت انجام می‌گیرد؛ یعنی مواد اولیه بدون واسطه به دست ما می‌رسد.',
      'حذف واسطه هم سود بیشتری برای کشاورز به همراه دارد و هم محصول تازه‌تر را با قیمت منصفانه‌تر به کارخانه‌های شما می‌رساند.',
    ],
    image: '/gallery/AQ8A1526AQ8A1526.webp',
  },
  {
    id: 'pistachio-export-gulf',
    category: 'export',
    date: '۱۴۰۴/۰۴/۱۲',
    title: 'صادرات محموله خلال و مغز پسته به بازارهای خلیج فارس',
    excerpt: 'محموله‌های خلال و مغز پسته پس از کنترل کیفی و با اسناد آزمایشگاهی کامل، راهی امارات و قطر می‌شوند.',
    body: [
      'مغز و خلال پسته قزوین، پس از کنترل رنگ، ضخامت برش و رطوبت، برای صادرات به بازارهای امارات و قطر آماده‌سازی می‌شود.',
      'هر محموله با اسناد آزمایشگاهی، فاکتور رسمی و اسناد گمرکی همراه می‌شود تا مسیر ترخیص مشتری بدون وقفه پیش برود.',
      'بازارهای صادراتی فعال هفت‌طلایی شامل امارات، قطر، عمان، عراق و افغانستان است و بخشی از فروش اروپا از طریق بازرگانان انجام می‌شود.',
    ],
    image: '/gallery/AQ8A1571AQ8A1571.webp',
  },
  {
    id: 'quality-lab-docs',
    category: 'quality',
    date: '۱۴۰۴/۰۳/۲۵',
    title: 'کنترل کیفی پیش از ارسال و ارسال اسناد آزمایشگاهی',
    excerpt: 'رطوبت، رنگ و سلامت هر محموله پیش از ارسال سنجیده می‌شود و اسناد آزمایشگاهی همراه بار فرستاده می‌شود.',
    body: [
      'پیش از هر ارسال، رطوبت، رنگ و سلامت محموله در واحد کنترل کیفی سنجیده می‌شود.',
      'اسناد آزمایشگاهی و فاکتور رسمی همراه بار ارسال می‌شود تا مشتری سابقه کیفی محموله را در دست داشته باشد.',
      'امکان ردیابی محموله از مرحله تأمین مواد اولیه تا بسته‌بندی نهایی فراهم است.',
    ],
    image: '/gallery/AQ8A1600AQ8A1600.webp',
  },
  {
    id: 'hazelnut-paste-line',
    category: 'production',
    date: '۱۴۰۴/۰۳/۰۸',
    title: 'خمیر، گرانول و پودر فندق برای صنایع شکلات و بستنی',
    excerpt: 'خط فندق هفت‌طلایی مشتقات فندق را از مغز خام و رست تا خمیر، گرانول و پودر فندق پوشش می‌دهد.',
    body: [
      'خط فندق ما به فرآوری مغز فندق، فندق خندان و مشتقات آن اختصاص دارد.',
      'خروجی این خط شامل مغز فندق خام و رست، خمیر فندق، گرانول و پودر فندق است؛ همان گریدهایی که صنایع شکلات، کیک و بستنی به آن نیاز دارند.',
      'بسته‌بندی در کیسه‌های ۱۰ و ۲۵ کیلوگرمی و بشکه صنعتی انجام می‌شود.',
    ],
    image: '/banner/hazelnut-spoon.webp',
  },
  {
    id: 'pistachio-harvest',
    category: 'production',
    date: '۱۴۰۴/۰۲/۲۰',
    title: 'پسته بوئین‌زهرا و کرمان؛ آماده‌سازی فصل برداشت',
    excerpt: 'پسته از باغ‌های بوئین‌زهرا و کرمان تأمین می‌شود؛ مغز پسته سبز برای شکلات و بستنی و خلال یکنواخت برای قنادی.',
    body: [
      'پسته مورد استفاده هفت‌طلایی از باغ‌های بوئین‌زهرا در قزوین و کرمان تأمین می‌شود.',
      'مغز پسته سبز برای شکلات و بستنی و خلال پسته با برش یکنواخت برای قنادی و تزئین عرضه می‌شود.',
      'هر محموله از برداشت تا بسته‌بندی سنجیده می‌شود تا رنگ و برش یکدست بماند.',
    ],
    image: '/banner/pistachio-kernels.webp',
  },
  {
    id: 'almond-slice-grade',
    category: 'production',
    date: '۱۴۰۴/۰۲/۰۵',
    title: 'خلال بادام درختی و زمینی با برش یکنواخت صنعتی',
    excerpt: 'خلال بادام درختی و بادام زمینی با ضخامت یکنواخت برش می‌خورد؛ همان چیزی که قنادی‌ها برای فرمولاسیون یکدست لازم دارند.',
    body: [
      'خلال بادام درختی و خلال بادام زمینی با ضخامت یکنواخت برش داده می‌شود تا فرمولاسیون قنادی و کیک‌سازی یکدست بماند.',
      'پرک و مغز بادام درختی نیز با شکستگی کنترل‌شده و رطوبت استاندارد عرضه می‌شود.',
      'عرضه این گریدها هم برای بازار داخلی و هم به‌صورت سفارشی برای صادرات انجام می‌شود.',
    ],
    image: '/banner/almond-milk.webp',
  },
  {
    id: 'factory-tour',
    category: 'exhibition',
    date: '۱۴۰۴/۰۱/۲۲',
    title: 'بازدید از خطوط فرآوری و بسته‌بندی هفت‌طلایی',
    excerpt: 'تصاویر و ویدئوهای تازه از سالن فرآوری، خطوط بسته‌بندی و محیط کارخانه در قزوین منتشر شد.',
    body: [
      'گزارش تصویری و ویدئویی تازه از سالن فرآوری، خطوط بسته‌بندی و محیط کارخانه هفت‌طلایی در قزوین منتشر شد.',
      'دو خط تولید جداگانه فعال است: یکی مخصوص فندق و مشتقاتش و دیگری برای پسته قزوین و کرمان.',
      'بازدیدهای کاری از کارخانه برای خریداران عمده با هماهنگی واحد بازرگانی انجام می‌شود.',
    ],
    image: '/gallery/AQ8A1640AQ8A1640.webp',
  },
  {
    id: 'trade-desk-hours',
    category: 'announcement',
    date: '۱۴۰۴/۰۱/۱۰',
    title: 'اطلاعیه: ساعات پاسخگویی واحد بازرگانی',
    excerpt: 'واحد بازرگانی هفت‌طلایی در روزهای کاری از طریق تلفن و ایمیل پاسخگوی درخواست قیمت و نمونه است.',
    body: [
      'واحد بازرگانی هفت‌طلایی در روزهای کاری از طریق تلفن ۰۲۸۳۳۲۳۴۰۰۴ و ۰۹۱۲۱۸۲۳۴۳۸ و ایمیل info@7golden.co پاسخگوی شماست.',
      'برای دریافت قیمت و نمونه، مشخصات گرید، حجم سفارش و مقصد تحویل را اعلام کنید تا پیشنهاد دقیق آماده شود.',
      'دفتر مرکزی در قزوین، سعدی جنوبی، نرسیده به بازار، پلاک ۲۱۰ و کارخانه در بلوار ابوترابی، نرسیده به سه راه شهر صنعتی قرار دارد.',
    ],
    image: '/gallery/AQ8A1742AQ8A1742.webp',
  },
];

// Trade-show & facility images captured across the 7Golden journey.
// Files live in public/gallery/.
export const PHOTOS = [
  '/gallery/AQ8A1495AQ8A1495.webp',
  '/gallery/AQ8A1498AQ8A1498.webp',
  '/gallery/AQ8A1499AQ8A1499.webp',
  '/gallery/AQ8A1502AQ8A1502.webp',
  '/gallery/AQ8A1505AQ8A1505.webp',
  '/gallery/AQ8A1508AQ8A1508.webp',
  '/gallery/AQ8A1511AQ8A1511.webp',
  '/gallery/AQ8A1513AQ8A1513.webp',
  '/gallery/AQ8A1516AQ8A1516.webp',
  '/gallery/AQ8A1517AQ8A1517.webp',
  '/gallery/AQ8A1520AQ8A1520.webp',
  '/gallery/AQ8A1524AQ8A1524.webp',
  '/gallery/AQ8A1525AQ8A1525.webp',
  '/gallery/AQ8A1526AQ8A1526.webp',
  '/gallery/AQ8A1527AQ8A1527.webp',
  '/gallery/AQ8A1528AQ8A1528.webp',
  '/gallery/AQ8A1529AQ8A1529.webp',
  '/gallery/AQ8A1530AQ8A1530.webp',
  '/gallery/AQ8A1531AQ8A1531.webp',
  '/gallery/AQ8A1534AQ8A1534.webp',
  '/gallery/AQ8A1537AQ8A1537.webp',
  '/gallery/AQ8A1538AQ8A1538.webp',
  '/gallery/AQ8A1539AQ8A1539.webp',
  '/gallery/AQ8A1541AQ8A1541.webp',
  '/gallery/AQ8A1542AQ8A1542.webp',
  '/gallery/AQ8A1543AQ8A1543.webp',
  '/gallery/AQ8A1544AQ8A1544.webp',
  '/gallery/AQ8A1545AQ8A1545.webp',
  '/gallery/AQ8A1547AQ8A1547.webp',
  '/gallery/AQ8A1550AQ8A1550.webp',
  '/gallery/AQ8A1552AQ8A1552.webp',
  '/gallery/AQ8A1562AQ8A1562.webp',
  '/gallery/AQ8A1563AQ8A1563.webp',
  '/gallery/AQ8A1568AQ8A1568.webp',
  '/gallery/AQ8A1571AQ8A1571.webp',
  '/gallery/AQ8A1579AQ8A1579.webp',
  '/gallery/AQ8A1581AQ8A1581.webp',
  '/gallery/AQ8A1584AQ8A1584.webp',
  '/gallery/AQ8A1589AQ8A1589.webp',
  '/gallery/AQ8A1590AQ8A1590.webp',
  '/gallery/AQ8A1595AQ8A1595.webp',
  '/gallery/AQ8A1597AQ8A1597.webp',
  '/gallery/AQ8A1600AQ8A1600.webp',
  '/gallery/AQ8A1605AQ8A1605.webp',
  '/gallery/AQ8A1606AQ8A1606.webp',
  '/gallery/AQ8A1612AQ8A1612.webp',
  '/gallery/AQ8A1614AQ8A1614.webp',
  '/gallery/AQ8A1618AQ8A1618.webp',
  '/gallery/AQ8A1621AQ8A1621.webp',
  '/gallery/AQ8A1622AQ8A1622.webp',
  '/gallery/AQ8A1624AQ8A1624.webp',
  '/gallery/AQ8A1625AQ8A1625.webp',
  '/gallery/AQ8A1628AQ8A1628.webp',
  '/gallery/AQ8A1631AQ8A1631.webp',
  '/gallery/AQ8A1640AQ8A1640.webp',
  '/gallery/AQ8A1641AQ8A1641.webp',
  '/gallery/AQ8A1650AQ8A1650.webp',
  '/gallery/AQ8A1665AQ8A1665.webp',
  '/gallery/AQ8A1666AQ8A1666.webp',
  '/gallery/AQ8A1667AQ8A1667.webp',
  '/gallery/AQ8A1671AQ8A1671.webp',
  '/gallery/AQ8A1676AQ8A1676.webp',
  '/gallery/AQ8A1681AQ8A1681.webp',
  '/gallery/AQ8A1682AQ8A1682.webp',
  '/gallery/AQ8A1683AQ8A1683.webp',
  '/gallery/AQ8A1688AQ8A1688.webp',
  '/gallery/AQ8A1702AQ8A1702.webp',
  '/gallery/AQ8A1706AQ8A1706.webp',
  '/gallery/AQ8A1708AQ8A1708.webp',
  '/gallery/AQ8A1716AQ8A1716.webp',
  '/gallery/AQ8A1717AQ8A1717.webp',
  '/gallery/AQ8A1721AQ8A1721.webp',
  '/gallery/AQ8A1729AQ8A1729.webp',
  '/gallery/AQ8A1732AQ8A1732.webp',
  '/gallery/AQ8A1734AQ8A1734.webp',
  '/gallery/AQ8A1735AQ8A1735.webp',
  '/gallery/AQ8A1737AQ8A1737.webp',
  '/gallery/AQ8A1742AQ8A1742.webp',
  '/gallery/AQ8A1748AQ8A1748.webp',
  '/gallery/AQ8A1750AQ8A1750.webp',
  '/gallery/AQ8A1752AQ8A1752.webp',
  '/gallery/AQ8A1768AQ8A1768.webp',
  '/gallery/AQ8A1770AQ8A1770.webp',
  '/gallery/AQ8A1771AQ8A1771.webp',
  '/gallery/AQ8A1773AQ8A1773.webp',
];

// Facility, processing and showroom clips. Each entry maps to a file in public/video/.
export const VIDEOS = [
  { title: 'نمایشگاه محصولات', image: '/video/showroom-1.mp4', type: 'video/mp4' },
  { title: 'سالن فرآوری ۰۱', image: '/video/processing-1.mp4', type: 'video/mp4' },
  { title: 'نمایشگاه و غرفه', image: '/video/showroom-2.mp4', type: 'video/mp4' },
  { title: 'خط تولید ۰۲', image: '/video/processing-2.mp4', type: 'video/mp4' },
  { title: 'نمایشگاه بین‌المللی', image: '/video/showroom-3.mp4', type: 'video/mp4' },
  { title: 'فرآوری و بسته‌بندی', image: '/video/processing-3.mp4', type: 'video/mp4' },
  { title: 'حضور در نمایشگاه', image: '/video/showroom-4.mp4', type: 'video/mp4' },
  { title: 'محیط کارخانه ۰۱', image: '/video/facility-5384.mov', type: 'video/quicktime' },
  { title: 'محیط کارخانه ۰۲', image: '/video/facility-5387.mov', type: 'video/quicktime' },
  { title: 'تور کارخانه', image: '/video/facility-7a8d.mov', type: 'video/quicktime' },
];
