// ===== Products from 7golden.co =====
// 3 categories: Hazelnut (7), Pistachio (7), Almond (6) = 20 products

export const PRODUCTS = [
  // ===== HAZELNUT (فندق) — 7 products =====
  {
    id: 'brain-hazelnut',
    type: 'hazelnut',
    category: 'hazelnut',
    nameFA: 'مغز فندق',
    nameEN: 'Raw Hazelnut Kernels',
    descFA: 'مغز فندق با روکش قهوه‌ای خود در سایزهای ۱۰-۱۳، ۱۳-۱۱ و ۱۱ – (دراژه). مناسب مصرف بازار خشکبار، صنایع بسته‌بندی، آجیل‌فروشان و فروشگاه‌ها. مغز فندق ایرانی به دلیل شرایط اقلیمی و خاکی مناسب، کیفیت بالا و طعم شیرین و خامه‌ای دارد و در صنایع شیرینی‌جات، بستنی و شکلات استفاده می‌شود.',
    descEN: 'Raw hazelnut kernels with brown coating in sizes 10-13, 13-11, and 11 (dragée). Suitable for dried fruit markets, packaging industries, nut sellers, and stores. Iranian hazelnut kernels have high quality and a sweet, creamy flavor due to favorable climatic conditions, and are used in confectionery, ice cream, and chocolate industries.',
    originFA: 'قزوین و اشنویه، ایران',
    originEN: 'Qazvin & Oshnavieh, Iran',
    price: 580000,
    priceDisplay: '۵۸۰٬۰۰۰',
    image: 'https://7golden.co/wp-content/uploads/2022/09/brain-hazelnut-7golden.png',
    badge: 'پرفروش',
    badgeEN: 'Best Seller',
    taste: { bitter: 25, sweet: 60, earthy: 70, nutty: 90 },
    weights: [250, 500, 1000],
    inStock: true,
    featured: true,
  },
  {
    id: 'roasted-hazelnut-brain',
    type: 'hazelnut',
    category: 'hazelnut',
    nameFA: 'مغز فندق رست',
    nameEN: 'Roasted Hazelnut Kernels',
    descFA: 'مغز فندق رست (سفید) در سایزهای ۱۰-۱۳، ۱۳-۱۱ و ۱۱ – (دراژه). مناسب مصرف بازار خشکبار، صنایع بسته‌بندی، آجیل‌فروشان و فروشگاه‌ها. بسته‌بندی در وزن‌های ۱۰، ۴۰ و ۵۰ کیلویی.',
    descEN: 'Roasted hazelnut kernels (white) in sizes 10-13, 13-11, and 11 (dragée). Suitable for dried fruit markets, packaging industries, nut sellers, and stores. Packaged in 10, 40, and 50 kg weights.',
    originFA: 'قزوین، ایران',
    originEN: 'Qazvin, Iran',
    price: 620000,
    priceDisplay: '۶۲۰٬۰۰۰',
    image: 'https://7golden.co/wp-content/uploads/2023/08/Roasted-hazelnut-brain-7goldenco.png',
    badge: null,
    taste: { bitter: 20, sweet: 75, earthy: 55, nutty: 95 },
    weights: [250, 500, 1000],
    inStock: true,
    featured: true,
  },
  {
    id: 'hazelnut-paste',
    type: 'hazelnut',
    category: 'hazelnut',
    nameFA: 'خمیر فندق',
    nameEN: 'Hazelnut Paste',
    descFA: 'خمیر فندق یکی از فرآورده‌های بسیار مهم فندق در تهیه انواع غذاها و چاشنی‌ها می‌باشد. مناسب برای مصرف در کارخانجات شیرینی و شکلات، بستنی و صنایع وابسته. بسته‌بندی در وزن‌های ۸ کیلوگرمی.',
    descEN: 'Hazelnut paste is one of the most important hazelnut derivatives used in preparing various foods and seasonings. Suitable for confectionery and chocolate factories, ice cream, and related industries. Packaged in 8 kg weights.',
    originFA: 'قزوین، ایران',
    originEN: 'Qazvin, Iran',
    price: 890000,
    priceDisplay: '۸۹۰٬۰۰۰',
    image: 'https://7golden.co/wp-content/uploads/2023/08/Hazelnut-paste-7golden.png',
    badge: 'ویژه',
    badgeEN: 'Special',
    taste: { bitter: 15, sweet: 80, earthy: 40, nutty: 98 },
    weights: [500, 1000],
    inStock: true,
    featured: true,
  },
  {
    id: 'hazelnut-powder',
    type: 'hazelnut',
    category: 'hazelnut',
    nameFA: 'پودر فندق',
    nameEN: 'Hazelnut Powder',
    descFA: 'پودر مغز فندق رست. مناسب مصرف کارخانه‌جات شیرینی و شکلات، بستنی و صنایع وابسته. بسته‌بندی در وزن‌های ۱۰ کیلوگرمی.',
    descEN: 'Roasted hazelnut kernel powder. Suitable for confectionery and chocolate factories, ice cream, and related industries. Packaged in 10 kg weights.',
    originFA: 'قزوین، ایران',
    originEN: 'Qazvin, Iran',
    price: 750000,
    priceDisplay: '۷۵۰٬۰۰۰',
    image: 'https://7golden.co/wp-content/uploads/2023/08/Hazelnut-powder-7golden.png',
    badge: null,
    taste: { bitter: 18, sweet: 70, earthy: 45, nutty: 88 },
    weights: [500, 1000],
    inStock: true,
    featured: false,
  },
  {
    id: 'smiling-hazelnut',
    type: 'hazelnut',
    category: 'hazelnut',
    nameFA: 'فندق خندان',
    nameEN: 'Smiling (Cracked) Hazelnuts',
    descFA: 'فندق ترک داده شده که به صورت دستی و دستگاهی موجود می‌باشد. مناسب مصرف بازار خشکبار، صنایع بسته‌بندی، آجیل‌فروشان و فروشگاه‌ها. بسته‌بندی در وزن‌های ۱۰، ۴۰ و ۵۰ کیلوگرمی.',
    descEN: 'Cracked hazelnuts available both manually and machine-processed. Suitable for dried fruit markets, packaging industries, nut sellers, and stores. Packaged in 10, 40, and 50 kg weights.',
    originFA: 'اشنویه، قزوین و اشکوارات شمال',
    originEN: 'Oshnavieh, Qazvin & Northern Ashkourat',
    price: 490000,
    priceDisplay: '۴۹۰٬۰۰۰',
    image: 'https://7golden.co/wp-content/uploads/2023/08/smiling-hazelnut-7golden.png',
    gallery: [
      'https://7golden.co/wp-content/uploads/2023/08/smiling-hazelnut-7golden.png',
      'https://7golden.co/wp-content/uploads/2023/08/5.jpeg',
    ],
    badge: 'جدید',
    badgeEN: 'New',
    taste: { bitter: 20, sweet: 65, earthy: 65, nutty: 88 },
    weights: [500, 1000],
    inStock: true,
    featured: false,
  },
  {
    id: 'hazelnut-skin',
    type: 'hazelnut',
    category: 'hazelnut',
    nameFA: 'پوست فندق',
    nameEN: 'Hazelnut Skin',
    descFA: 'مورد استفاده در صنعت ذغال و چوب و صنایع وابسته به صورت فله.',
    descEN: 'Used in charcoal and wood industries and related sectors, sold in bulk.',
    originFA: 'قزوین، ایران',
    originEN: 'Qazvin, Iran',
    price: 120000,
    priceDisplay: '۱۲۰٬۰۰۰',
    image: 'https://7golden.co/wp-content/uploads/2023/08/Hazelnut-skin-7golden.png',
    badge: null,
    taste: { bitter: 40, sweet: 10, earthy: 80, nutty: 30 },
    weights: [1000],
    inStock: true,
    featured: false,
  },
  {
    id: 'hazelnut-granules',
    type: 'hazelnut',
    category: 'hazelnut',
    nameFA: 'گرانول فندق',
    nameEN: 'Hazelnut Granules',
    descFA: 'مناسب برای مصرف در کارخانجات شیرینی و شکلات، بستنی و صنایع وابسته. بسته‌بندی در وزن‌های ۸ کیلوگرمی.',
    descEN: 'Suitable for use in confectionery and chocolate factories, ice cream, and related industries. Packaged in 8 kg weights.',
    originFA: 'قزوین، ایران',
    originEN: 'Qazvin, Iran',
    price: 820000,
    priceDisplay: '۸۲۰٬۰۰۰',
    image: 'https://7golden.co/wp-content/uploads/2023/08/Hazelnut-granules-7goldenco.png',
    badge: null,
    taste: { bitter: 15, sweet: 72, earthy: 42, nutty: 92 },
    weights: [500, 1000],
    inStock: true,
    featured: false,
  },

  // ===== PISTACHIO (پسته) — 7 products =====
  {
    id: 'qazvin-pistachio-nuts',
    type: 'pistachio',
    category: 'pistachio',
    nameFA: 'مغز پسته قزوین',
    nameEN: 'Qazvin Pistachio Kernels',
    descFA: 'مغز پسته قزوین یکی از معروف‌ترین مغزهای پسته دنیا می‌باشد که به علت طعم و رنگ آن این محصول را بسیار خاص کرده است. مناسب برای صادرات، صنایع بسته‌بندی، شرکت‌های باقلوا، حلوا ارده و آجیل‌فروشان. بسته‌بندی در بسته‌های ۱۰ و ۴۰ کیلوگرم.',
    descEN: 'Qazvin pistachio kernels are among the most famous in the world, made unique by their flavor and color. Suitable for export, packaging industries, baklava companies, tahini halva, and nut sellers. Packaged in 10 and 40 kg bags.',
    originFA: 'بوئین‌زهرا، قزوین',
    originEN: 'Buin Zahra, Qazvin',
    price: 1250000,
    priceDisplay: '۱٬۲۵۰٬۰۰۰',
    image: 'https://7golden.co/wp-content/uploads/2022/09/Qazvin-pistachio-nuts-7goldenco.png',
    gallery: [
      'https://7golden.co/wp-content/uploads/2022/09/Qazvin-pistachio-nuts-7goldenco.png',
      'https://7golden.co/wp-content/uploads/2023/08/IN-TEXT_ANG1528-1-2000x1184-1.jpg',
    ],
    badge: 'صادراتی',
    badgeEN: 'Export Grade',
    taste: { bitter: 30, sweet: 55, earthy: 45, nutty: 85 },
    weights: [250, 500, 1000],
    inStock: true,
    featured: true,
  },
  {
    id: 'qazvini-peeled-pistachio-nuts',
    type: 'pistachio',
    category: 'pistachio',
    nameFA: 'مغز پسته پوست کنده قزوینی',
    nameEN: 'Peeled Qazvin Pistachio Kernels',
    descFA: 'مغز پسته قزوین یکی از معروف‌ترین مغزهای پسته دنیا می‌باشد که به علت رنگ سبز آن این محصول را بسیار خاص کرده است. مناسب برای صادرات، صنایع بسته‌بندی، شرکت‌های باقلوا، حلوا ارده و آجیل‌فروشان. بسته‌بندی در بسته‌های ۱۰ و ۴۰ کیلوگرمی.',
    descEN: 'Peeled Qazvin pistachio kernels, among the most famous in the world, made unique by their green color. Suitable for export, packaging industries, baklava companies, tahini halva, and nut sellers. Packaged in 10 and 40 kg bags.',
    originFA: 'بوئین‌زهرا، قزوین',
    originEN: 'Buin Zahra, Qazvin',
    price: 1450000,
    priceDisplay: '۱٬۴۵۰٬۰۰۰',
    image: 'https://7golden.co/wp-content/uploads/2022/09/qazvini-peeled-pistachio-nuts-7goldenco.png',
    gallery: [
      'https://7golden.co/wp-content/uploads/2022/09/qazvini-peeled-pistachio-nuts-7goldenco.png',
      'https://7golden.co/wp-content/uploads/2023/08/11.jpeg',
    ],
    badge: null,
    taste: { bitter: 25, sweet: 60, earthy: 40, nutty: 88 },
    weights: [250, 500, 1000],
    inStock: true,
    featured: false,
  },
  {
    id: 'qazvin-pistachio-slices',
    type: 'pistachio',
    category: 'pistachio',
    nameFA: 'خلال پسته قزوین',
    nameEN: 'Qazvin Pistachio Slices',
    descFA: 'خلال پسته قزوین به علت رنگ سبز بی‌نظیر خود از جمله منحصر‌به‌فردترین خلال پسته‌های دنیا به شمار می‌رود. مناسب برای صادرات، صنایع بسته‌بندی، شرکت‌های باقلوا، حلوا ارده و آجیل‌فروشان و رستوران‌ها. بسته‌بندی در بسته‌های ۱۰ و ۲۲ کیلوگرمی.',
    descEN: 'Qazvin pistachio slices are among the most unique in the world due to their unparalleled green color. Suitable for export, packaging industries, baklava companies, tahini halva, nut sellers, and restaurants. Packaged in 10 and 22 kg bags.',
    originFA: 'بوئین‌زهرا، قزوین',
    originEN: 'Buin Zahra, Qazvin',
    price: 1380000,
    priceDisplay: '۱٬۳۸۰٬۰۰۰',
    image: 'https://7golden.co/wp-content/uploads/2022/09/khelal-qazvin-slice-7golden.png',
    badge: 'محبوب',
    badgeEN: 'Popular',
    taste: { bitter: 25, sweet: 50, earthy: 40, nutty: 80 },
    weights: [250, 500, 1000],
    inStock: true,
    featured: true,
  },
  {
    id: 'pistachio-powder',
    type: 'pistachio',
    category: 'pistachio',
    nameFA: 'پودر پسته',
    nameEN: 'Pistachio Powder',
    descFA: 'پودر مغز پسته یکی از فراورده‌های پسته می‌باشد که کاربردهای فراوانی در صنایع شیرینی‌پزی و تهیه و تزیین انواع کیک، شکلات، بستنی و خمیر پسته دارد. بسته‌بندی در وزن‌های ۸ و ۱۵ کیلوگرمی.',
    descEN: 'Pistachio kernel powder is a pistachio derivative widely used in pastry industries and in preparing and decorating cakes, chocolates, ice cream, and pistachio paste. Packaged in 8 and 15 kg weights.',
    originFA: 'قزوین، ایران',
    originEN: 'Qazvin, Iran',
    price: 960000,
    priceDisplay: '۹۶۰٬۰۰۰',
    image: 'https://7golden.co/wp-content/uploads/2022/09/Pistachio-powder-7golden.png',
    badge: null,
    taste: { bitter: 20, sweet: 45, earthy: 35, nutty: 75 },
    weights: [500, 1000],
    inStock: true,
    featured: true,
  },
  {
    id: 'raw-pistachios',
    type: 'pistachio',
    category: 'pistachio',
    nameFA: 'پسته خام قزوین',
    nameEN: 'Raw Qazvin Pistachios',
    descFA: 'پسته قزوین به دلیل ارزش غذایی بالا و خواص درمانی مفید، به عنوان یکی از محصولات صادراتی مهم ایران به شمار می‌رود. بیشترین کاربرد پسته قزوین به دلیل سبز بودن مغز آن برای خلال استفاده می‌شود. بسته‌بندی در کیسه‌های ۴۰ و ۵۰ کیلویی.',
    descEN: 'Qazvin pistachios are considered one of Iran\'s important export products due to their high nutritional value and beneficial therapeutic properties. Their greatest use is in slices due to the green color of the kernel. Packaged in 40 and 50 kg bags.',
    originFA: 'بوئین‌زهرا، قزوین',
    originEN: 'Buin Zahra, Qazvin',
    price: 1100000,
    priceDisplay: '۱٬۱۰۰٬۰۰۰',
    image: 'https://7golden.co/wp-content/uploads/2022/09/raw-pistachios-7golden.png',
    badge: null,
    taste: { bitter: 28, sweet: 52, earthy: 48, nutty: 82 },
    weights: [500, 1000],
    inStock: true,
    featured: false,
  },
  {
    id: 'kermani-pistachio-slices',
    type: 'pistachio',
    category: 'pistachio',
    nameFA: 'خلال پسته کرمانی',
    nameEN: 'Kermani Pistachio Slices',
    descFA: 'خلال پسته کرمانی. مناسب جهت صادرات، صنایع بسته‌بندی، شرکت‌های تولید کننده باقلوا، حلوا ارده و آجیل‌فروشان و رستوران‌ها. بسته‌بندی در وزن‌های ۱۰ و ۲۲ کیلوگرمی.',
    descEN: 'Kermani pistachio slices. Suitable for export, packaging industries, baklava producers, tahini halva, nut sellers, and restaurants. Packaged in 10 and 22 kg weights.',
    originFA: 'کرمان، ایران',
    originEN: 'Kerman, Iran',
    price: 1280000,
    priceDisplay: '۱٬۲۸۰٬۰۰۰',
    image: 'https://7golden.co/wp-content/uploads/2022/09/kermani-khelal-7golden.png',
    badge: null,
    taste: { bitter: 22, sweet: 55, earthy: 42, nutty: 78 },
    weights: [250, 500, 1000],
    inStock: true,
    featured: false,
  },
  {
    id: 'pistachio-skin',
    type: 'pistachio',
    category: 'pistachio',
    nameFA: 'پوست پسته',
    nameEN: 'Pistachio Skin',
    descFA: 'مورد استفاده در صنعت ذغال و چوب و صنایع وابسته. بسته‌بندی به صورت فله.',
    descEN: 'Used in charcoal and wood industries and related sectors. Packaged in bulk.',
    originFA: 'قزوین، ایران',
    originEN: 'Qazvin, Iran',
    price: 150000,
    priceDisplay: '۱۵۰٬۰۰۰',
    image: 'https://7golden.co/wp-content/uploads/2022/09/pistachio-skin-7golden.png',
    badge: null,
    taste: { bitter: 45, sweet: 5, earthy: 85, nutty: 20 },
    weights: [1000],
    inStock: true,
    featured: false,
  },

  // ===== ALMOND (بادام) — 6 products =====
  {
    id: 'almond-flakes',
    type: 'almond',
    category: 'almond',
    nameFA: 'پرک بادام',
    nameEN: 'Almond Flakes',
    descFA: 'پرک بادام درختی به دلیل ۴ قسمت شدن هر مغز بادام ظاهری بسیار شکیل داشته. مناسب مصرف در صنایع شکلات‌سازی، حلوا شکری، سوهان، تولید بستنی، قنادی و... بسته‌بندی در وزن‌های ۸ کیلوگرمی.',
    descEN: 'Tree almond flakes have a very elegant appearance due to each almond kernel being divided into four parts. Suitable for chocolate making, sugar halva, sohan, ice cream production, confectionery, and more. Packaged in 8 kg weights.',
    originFA: 'ایران',
    originEN: 'Iran',
    price: 780000,
    priceDisplay: '۷۸۰٬۰۰۰',
    image: 'https://7golden.co/wp-content/uploads/2023/08/almond-flakes-7golden.png',
    badge: null,
    taste: { bitter: 15, sweet: 65, earthy: 50, nutty: 85 },
    weights: [250, 500, 1000],
    inStock: true,
    featured: true,
  },
  {
    id: 'almond-powder',
    type: 'almond',
    category: 'almond',
    nameFA: 'پودر بادام',
    nameEN: 'Almond Powder',
    descFA: 'پودر مغز بادام یکی از فرآورده‌های بادام می‌باشد که در صنایع شیرینی‌پزی و کیک‌پزی و شکلات‌سازی بسیار پرکاربرد می‌باشد. بسته‌بندی در وزن‌های ۱۰ و ۱۵ کیلوگرمی.',
    descEN: 'Almond kernel powder is an almond derivative widely used in pastry, cake baking, and chocolate making industries. Packaged in 10 and 15 kg weights.',
    originFA: 'ایران',
    originEN: 'Iran',
    price: 690000,
    priceDisplay: '۶۹۰٬۰۰۰',
    image: 'https://7golden.co/wp-content/uploads/2023/08/almond-powder-7golden.png',
    badge: null,
    taste: { bitter: 12, sweet: 60, earthy: 45, nutty: 82 },
    weights: [500, 1000],
    inStock: true,
    featured: false,
  },
  {
    id: 'sliced-peanuts',
    type: 'almond',
    category: 'almond',
    nameFA: 'خلال بادام زمینی',
    nameEN: 'Sliced Peanuts',
    descFA: 'خلال بادام زمینی از نظر ارزش غذایی ارزشی برابر با مغز گردو و بادام دارد و منبعی غنی از پروتئین است. مناسب مصرف صنایع شیرینی‌پزی و شکلات‌سازی و کیک‌پزی و سوهان. بسته‌بندی در وزن‌های ۱۰ و ۲۰ کیلوگرمی.',
    descEN: 'Sliced peanuts have nutritional value equal to walnuts and almonds and are a rich source of protein. Suitable for pastry, chocolate making, cake baking, and sohan industries. Packaged in 10 and 20 kg weights.',
    originFA: 'ایران',
    originEN: 'Iran',
    price: 320000,
    priceDisplay: '۳۲۰٬۰۰۰',
    image: 'https://7golden.co/wp-content/uploads/2023/08/sliced-peanuts-7golden.png',
    badge: null,
    taste: { bitter: 10, sweet: 55, earthy: 60, nutty: 90 },
    weights: [500, 1000],
    inStock: true,
    featured: false,
  },
  {
    id: 'nuts-of-tree-almonds',
    type: 'almond',
    category: 'almond',
    nameFA: 'مغز بادام درختی',
    nameEN: 'Tree Almond Kernels',
    descFA: 'مغز بادام با روکش قهوه‌ای خاص خود در سایزهای مختلف. مناسب مصرف در بازار، شرکت‌های کیک و شکلات و صنایع وابسته. بسته‌بندی در وزن‌های ۴۵ کیلوگرمی.',
    descEN: 'Almond kernels with their special brown coating in various sizes. Suitable for markets, cake and chocolate companies, and related industries. Packaged in 45 kg weights.',
    originFA: 'ایران',
    originEN: 'Iran',
    price: 850000,
    priceDisplay: '۸۵۰٬۰۰۰',
    image: 'https://7golden.co/wp-content/uploads/2023/08/Nuts-of-tree-almonds-7golden.png',
    badge: null,
    taste: { bitter: 18, sweet: 62, earthy: 48, nutty: 87 },
    weights: [250, 500, 1000],
    inStock: true,
    featured: true,
  },
  {
    id: 'sliced-almonds',
    type: 'almond',
    category: 'almond',
    nameFA: 'خلال بادام درختی',
    nameEN: 'Sliced Almonds',
    descFA: 'خلال بادام در تهیه و تزیین انواع غذاها، شیرینی‌جات، شکلات‌ها و دسرها به کار برده می‌شود. بسته‌بندی در وزن‌های ۸ و ۱۸ کیلوگرمی.',
    descEN: 'Sliced almonds are used in preparing and decorating various foods, sweets, chocolates, and desserts. Packaged in 8 and 18 kg weights.',
    originFA: 'ایران',
    originEN: 'Iran',
    price: 820000,
    priceDisplay: '۸۲۰٬۰۰۰',
    image: 'https://7golden.co/wp-content/uploads/2023/08/badam-1024x683-1.png',
    badge: null,
    taste: { bitter: 14, sweet: 63, earthy: 47, nutty: 84 },
    weights: [250, 500, 1000],
    inStock: true,
    featured: false,
  },
  {
    id: 'peanuts-without-skin',
    type: 'almond',
    category: 'almond',
    nameFA: 'مغز بادام زمینی بدون پوست',
    nameEN: 'Peanuts Without Skin',
    descFA: 'مغز بادام زمینی سفید در تهیه محصولات نظیر خلال بادام زمینی، شیرینی‌ها، کیک‌ها و دسرها بسیار رایج است. همچنین می‌تواند به عنوان تنقلات سالم و پرانرژی مصرف شود. بسته‌بندی در کارتن‌های ۲۵ کیلویی.',
    descEN: 'White peanut kernels are commonly used in making products such as sliced peanuts, sweets, cakes, and desserts. They can also be consumed as a healthy, high-energy snack. Packaged in 25 kg cartons.',
    originFA: 'ایران',
    originEN: 'Iran',
    price: 380000,
    priceDisplay: '۳۸۰٬۰۰۰',
    image: 'https://7golden.co/wp-content/uploads/2023/08/peanuts-without-skin-7golden.png',
    badge: null,
    taste: { bitter: 8, sweet: 58, earthy: 55, nutty: 88 },
    weights: [500, 1000],
    inStock: true,
    featured: false,
  },
];

// ===== Categories (3 main — matching 7golden.co) =====
export const CATEGORIES = [
  {
    id: 'hazelnut',
    nameFA: 'فندق',
    nameEN: 'Hazelnut',
    descFA: 'مغز و مشتقات فندق — از باغستان‌های قزوین و اشنویه',
    descEN: 'Hazelnut kernels & derivatives — from Qazvin & Oshnavieh orchards',
    image: 'https://media.base44.com/images/public/6a80827227ffde1fa7218f17/9f86177f4_generated_image.png',
    count: PRODUCTS.filter(p => p.category === 'hazelnut').length,
  },
  {
    id: 'pistachio',
    nameFA: 'پسته',
    nameEN: 'Pistachio',
    descFA: 'مغز، خلال و پودر پسته — سبزترین پسته‌های ایران',
    descEN: 'Pistachio kernels, slices & powder — Iran\'s greenest pistachios',
    image: 'https://media.base44.com/images/public/6a80827227ffde1fa7218f17/ad191612c_generated_image.png',
    count: PRODUCTS.filter(p => p.category === 'pistachio').length,
  },
  {
    id: 'almond',
    nameFA: 'بادام',
    nameEN: 'Almond',
    descFA: 'مغز، پرک و خلال بادام — برای صنایع قنادی و شکلات',
    descEN: 'Almond kernels, flakes & slices — for confectionery & chocolate',
    image: 'https://media.base44.com/images/public/6a80827227ffde1fa7218f17/d08d6f216_generated_image.png',
    count: PRODUCTS.filter(p => p.category === 'almond').length,
  },
];

export const TESTIMONIALS = [
  {
    nameFA: 'سعید اکبری',
    nameEN: 'Saeid Akbari',
    roleFA: 'مدیر کارخانه شکلات‌سازی',
    roleEN: 'Chocolate Factory Manager',
    textFA: 'خمیر فندق هفت‌طلایی را سه ساله است استفاده می‌کنیم. کیفیت ثابت و ارسال به‌موقع دارند.',
    textEN: 'We\'ve used 7Golden\'s hazelnut paste for three years. Consistent quality and timely delivery.',
    rating: 5,
  },
  {
    nameFA: 'نیلوفر رضایی',
    nameEN: 'Niloofar Rezaei',
    roleFA: 'قنادی معروف تهران',
    roleEN: 'Renowned Tehran Pastry Chef',
    textFA: 'خلال پسته قزوینشان رنگ و طعم بی‌نظیری داره. مشتریامون همیشه تعریف می‌کنن.',
    textEN: 'Their Qazvin pistachio slices have an unmatched color and flavor. Our customers always compliment them.',
    rating: 5,
  },
  {
    nameFA: 'محمد حسینی',
    nameEN: 'Mohammad Hosseini',
    roleFA: 'واردکننده امارات',
    roleEN: 'UAE Importer',
    textFA: 'محصولات صادراتی هفت‌طلایی استاندارد بین‌المللی دارند و بازار خلیج فارس خوب پذیرفته.',
    textEN: '7Golden\'s export products meet international standards and are well-received in the Gulf market.',
    rating: 5,
  },
];

export const BLOG_POSTS = [
  {
    id: 1,
    titleFA: 'افتخارات هفت طلایی',
    titleEN: "7Golden's Honors",
    excerptFA: 'مجموعه خشکبار هفت طلایی در نمایشگاه‌ها و رویدادهای مختلف افتخارات متعددی کسب کرده است.',
    excerptEN: '7Golden Dried Fruits has earned numerous honors at various exhibitions and events.',
    date: '۴ جولای ۲۰۲۴',
    dateEN: 'July 4, 2024',
    category: 'news',
    image: 'https://7golden.co/wp-content/uploads/2022/09/blog-new-3-min.jpg',
  },
  {
    id: 2,
    titleFA: 'کاهش قدرت خرید و افزایش رقابت',
    titleEN: 'Decrease in Purchasing Power & Increased Competition',
    excerptFA: 'بررسی تأثیر کاهش قدرت خرید بر بازار خشکبار و راهکارهای رقابت در شرایط اقتصادی فعلی.',
    excerptEN: 'Examining the impact of decreased purchasing power on the dried fruit market and competitive strategies.',
    date: '۲۱ ژوئن ۲۰۲۴',
    dateEN: 'June 21, 2024',
    category: 'education',
    image: 'https://7golden.co/wp-content/uploads/2022/09/blog-new-4-min.jpg',
  },
  {
    id: 3,
    titleFA: 'نمایشگاه شیرینی شکلات ۱۴۰۲',
    titleEN: 'Sweets & Chocolate Exhibition 1402',
    excerptFA: 'مجموعه بزرگ خشکبار هفت طلایی در نمایشگاه شیرینی و شکلات ۱۴۰۲ درخشید و جایگاه ممتازی کسب کرد.',
    excerptEN: '7Golden Dried Fruits shined at the 1402 Sweets & Chocolate Exhibition and secured a distinguished position.',
    date: '۲۵ سپتامبر ۲۰۲۳',
    dateEN: 'September 25, 2023',
    category: 'news',
    image: 'https://7golden.co/wp-content/uploads/2023/09/AQ8A1663AQ8A1663-scaled.jpg',
  },
];