// Auto-generated by Base44 CLI - DO NOT EDIT
// Regenerate with: base44 types generate

export interface Award {
  /**
   * Persian title of license/award
   */
  title_fa: string;
  /**
   * English title of license/award
   */
  title_en: string;
  /**
   * Persian description
   */
  desc_fa?: string;
  /**
   * English description
   */
  desc_en?: string;
  /**
   * Image URL of the license/award
   */
  image: string;
  sort_order?: number;
  published?: boolean;
}

/**
 * Blog posts with bilingual support (Persian / English)
 */
export interface BlogPost {
  /**
   * URL-friendly unique identifier
   */
  slug: string;
  /**
   * Title in Persian
   */
  title_fa: string;
  /**
   * Title in English
   */
  title_en: string;
  /**
   * Short summary in Persian
   */
  excerpt_fa?: string;
  /**
   * Short summary in English
   */
  excerpt_en?: string;
  /**
   * Full article body (markdown or HTML)
   */
  content?: string;
  /**
   * Display date in Persian
   */
  date_fa?: string;
  /**
   * Display date in English
   */
  date_en?: string;
  /**
   * Category (news, education, etc.)
   */
  category?: string;
  /**
   * Cover image URL
   */
  image: string;
  /**
   * Whether the post is publicly visible
   */
  published?: boolean;
  /**
   * Manual sort order (lower = higher priority)
   */
  sort_order?: number;
}

export interface Category {
  slug: string;
  name_fa: string;
  name_en: string;
  desc_fa?: string;
  desc_en?: string;
  image: string;
  sort_order?: number;
}

export interface ContactMessage {
  name: string;
  phone?: string;
  email?: string;
  message: string;
  status?: "new" | "read" | "replied";
}

export interface GalleryImage {
  /**
   * Persian title for the gallery image
   */
  title_fa: string;
  /**
   * English title for the gallery image
   */
  title_en: string;
  /**
   * Persian caption/description
   */
  desc_fa?: string;
  /**
   * English caption/description
   */
  desc_en?: string;
  /**
   * Image URL
   */
  image: string;
  /**
   * Masonry layout sizing hint
   */
  span?: "tall" | "wide" | "normal";
  sort_order?: number;
  published?: boolean;
}

export interface Order {
  /**
   * Human-readable order number e.g. 7G-1042
   */
  order_number: string;
  /**
   * Tracking code for shipment
   */
  tracking_code: string;
  /**
   * Ordered line items
   */
  items: {
    name?: string;
    price?: number;
    qty?: number;
    weight?: number;
    image?: string;
  }[];
  /**
   * Cart subtotal before shipping
   */
  subtotal?: number;
  /**
   * Shipping cost in IRR
   */
  shipping_cost?: number;
  /**
   * Shipping method chosen
   */
  shipping_method?: "standard" | "express";
  /**
   * Total including shipping
   */
  grand_total: number;
  /**
   * Payment method
   */
  payment_method?: "online" | "cod";
  status?: "pending" | "processing" | "shipped" | "delivered" | "cancelled";
  full_name?: string;
  phone?: string;
  province?: string;
  address?: string;
  postal_code?: string;
}

export interface Product {
  /**
   * URL-friendly identifier, e.g. hazelnut-paste
   */
  slug: string;
  name_fa: string;
  name_en: string;
  desc_fa?: string;
  desc_en?: string;
  /**
   * Category slug: hazelnut, pistachio, almond
   */
  category: string;
  origin_fa?: string;
  origin_en?: string;
  /**
   * Price in IRR per kg
   */
  price: number;
  /**
   * Pre-formatted Persian numeral price string
   */
  price_display?: string;
  /**
   * Primary image URL
   */
  image: string;
  /**
   * Additional image URLs
   */
  gallery?: string[];
  /**
   * Persian badge label, null if none
   */
  badge?: string;
  /**
   * English badge label, null if none
   */
  badge_en?: string;
  /**
   * Taste profile percentages 0-100
   */
  taste?: {
    bitter?: number;
    sweet?: number;
    earthy?: number;
    nutty?: number;
  };
  /**
   * Available weights in grams
   */
  weights?: number[];
  in_stock?: boolean;
  featured?: boolean;
  /**
   * Whether the product is visible on the public storefront
   */
  published?: boolean;
  sort_order?: number;
}

export interface SiteSettings {
  site_name_fa: string;
  site_name_en: string;
  /**
   * Site mode: store (e-commerce with prices/cart) or corporate (showcase only, no prices)
   */
  site_mode?: "store" | "corporate";
  default_seo_title_fa?: string;
  default_seo_title_en?: string;
  default_seo_desc_fa?: string;
  default_seo_desc_en?: string;
  og_image?: string;
  logo_url?: string;
  contact_phone?: string;
  contact_mobile?: string;
  contact_email?: string;
  hq_address_fa?: string;
  hq_address_en?: string;
  tehran_address_fa?: string;
  tehran_address_en?: string;
  working_hours_fa?: string;
  working_hours_en?: string;
}

export interface Testimonial {
  name_fa: string;
  name_en: string;
  role_fa?: string;
  role_en?: string;
  text_fa: string;
  text_en: string;
  rating?: number;
  sort_order?: number;
}

export interface User {
  /**
   * The role of the user in the app
   */
  role: "admin" | "user";
}

declare module '@base44/sdk' {
  interface EntityTypeRegistry {
    "Award": Award;
    "BlogPost": BlogPost;
    "Category": Category;
    "ContactMessage": ContactMessage;
    "GalleryImage": GalleryImage;
    "Order": Order;
    "Product": Product;
    "SiteSettings": SiteSettings;
    "Testimonial": Testimonial;
    "User": User;
  }
  
  interface FunctionNameRegistry {
    "generateSitemap": true;
  }
  
  interface AgentNameRegistry {
    "support_agent": true;
  }
}